- .github/workflows/rules.yml
- .github/workflows/wheels.yml
- requirements.txt
- setup.py
- src/qibojit/__init__.py
- src/qibojit/custom_operators/backends.py
Extends CI to other operating systems. It seems that the cupy does not offer precompiled versions for macos. Unfortunately the pure `cupy` package is not simple to install on CI.
I believe we should consider removing cupy from the requirements of macos builds. I believe the code will crash if cupy is not installed, @stavros11 could you please have a look?
> Extending CI 

- .github/workflows/rules.yml
- .github/workflows/wheels.yml
- src/qibojit/custom_operators/gates.py
After upgrading to numba 0.54, I get:
```
UnsupportedRewriteError: Failed in nopython mode pipeline (step: convert to parfors)
Overwrite of parallel loop index
File "../qibojit/src/qibojit/custom_operators/gates.py", line 106:
def multicontrol_apply_z_pow_kernel(state, gate, qubits, nstates, m):
<source elided>
for g in prange(nstates):  # pylint: disable=not-an-iterable
i = multicontrol_index(g, qubits)
^
```
(see https://github.com/qiboteam/qibojit/runs/3393479978?check_suite_focus=true)
So, removing the inline seems to fix this issue.
> removing inline

- src/qibojit/custom_operators/__init__.py
- src/qibojit/custom_operators/backends.py
- src/qibojit/custom_operators/ops.py
- src/qibojit/tests/test_ops.py
Adds the transpose_state and swap_pieces ops required by the multi-GPU scheme that is currently implemented in qibo (see [#453](https://github.com/qiboteam/qibo/pull/453) for more details). This follows the qibotf implementation of these ops and adds them only on the numba CPU, not the cupy, as qibotf also does not provide CUDA kernels for these ops. In the multi-GPU they are only used by CPU to manipulate the state pieces before loading them on GPUs.
The transpose_state op can also be easily implemented using numpy primitives, for example see [here](https://github.com/qiboteam/qibo/blob/0079e9adda7655d0410e4b77367413f4acca2c86/src/qibo/backends/numpy.py#L405). I am not sure whether this pure numpy implementation is faster than the numba implemented here but we could benchmark and finally …
> Add ops required by qibo multi-GPU

- src/qibojit/custom_operators/__init__.py
- src/qibojit/custom_operators/backends.py
- src/qibojit/tests/test_backends.py
Closes #34.
- I fixed the ``rocblas_status_not_implemented`` issue by using NumPy instead of CuPy for ``eigh`` and ``eigvalsh``.
The changes apply only to CuPy with AMD GPUs.
- I completed the regression tests by running the tests on a machine with an AMD GPU and saving the output.
In order to close #34, we need also to merge https://github.com/qiboteam/qibo/pull/501 in the Qibo repository.
> Fix tests and methods with AMD ROCM

- src/qibojit/custom_operators/backends.py
- src/qibojit/custom_operators/gates.cu.cc
In this PR I implemented an alternative approach for the multi-qubit gate GPU kernels.
Instead of using hard-coded kernels + a general kernel that uses a copy of the state vector, here we use a general kernel
whose number of targets is passed as a template argument (actually ``2**ntargets``).
In this way, we match the speed of hard-coded kernels while having something which is easy to read and maintain.
The ``CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES`` raised in the hard-coded kernels was solved
by using the ``__launch_bounds__()`` command. Now we don't need to reduce the number of threads per block anymore.
Results are slightly worse than those of the hard-coded kernels, but better than the general one with the duplicated state vector (and we don't need to duplicate the state vector anymore).
I …
> Use template kernels for multiqubit gates

- src/qibojit/custom_operators/__init__.py
- src/qibojit/custom_operators/gates.py
It looks like we forgot to update the call to the multiqubit GPU kernels in ``JitCustomBackend`` after we moved the latter from qibo to qibojit.
> Fix multiqubit GPU ops not called by JitCustomBackend

- src/qibojit/custom_operators/gates.cu.cc
If I run a circuit with 32 qubits on GPU with the ``CupyBackend`` I get the following error:
```
File ".../qibojit/src/qibojit/custom_operators/backends.py", line 261, in one_qubit_base
self.cp.cuda.stream.get_current_stream().synchronize()
File "cupy/cuda/stream.pyx", line 221, in cupy.cuda.stream.BaseStream.synchronize
File "cupy_backends/cuda/api/runtime.pyx", line 894, in cupy_backends.cuda.api.runtime.streamSynchronize
File "cupy_backends/cuda/api/runtime.pyx", line 273, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
```
The problem is solved after fixing a cast from long to int in line 14 of ``gates.cu.cc``:
```
(long)(1 << n) -> ((long)1 << n)
```
Let me know if you …
> Fix ``CupyBackend`` crash with 32 qubits

- src/qibojit/custom_operators/backends.py
Closes #46. Linked PR in qibo repository:
The CPU fallback for some methods is not working properly. In order to fix it, we need to change the corresponding method in qibo, however we need NumbaBackend to be able to cast from CuPy arrays to Numpy ones.
As it is now, it is not possible because ``self.np.array(x)`` raises a ``TypeError``  if ``x`` is a CuPy array. We cannot check easily if ``x`` is a CuPy array because NumbaBackend is independent of CuPy.
As a temporary fix, I tried to catch a ``TypeError``, I don't know if this solution is optimal. @stavros11 what do you think?
> Fix CPU fallback

- src/qibojit/custom_operators/__init__.py
- src/qibojit/tests/test_backends.py
In some circumstances the CPU fallback for qibojit does not work. Here we ensure that all the arguments are properly converted from CuPy arrays to Numpy ones, so that the fallback does not fail.
> Implement a custom CPU fallback for qibojit

- src/qibojit/custom_operators/backends.py
Closes #47. While working to fix #47, I noticed that PR https://github.com/qiboteam/qibo/pull/528 do not resolve the problem with qibojit.
In fact, the cast method of CuPy doesn't change the dtype if the input array is already a CuPy array. I fixed it, and I also make some additional changes to improve the cast for both CuPy and Numba, because some times the dtype is ignored. Let me know your opinion.
> Fix cast method not changing dtype

- src/qibojit/custom_operators/backends.py
- src/qibojit/tests/test_gates.py
Following some issues mentioned in #57 regarding `qubits=None`, this adds some tests that check the `one_qubit_base` and `two_qubit_base` directly with `qubits == None` and `qubits != None` to make sure we have full coverage on GPU. I also fixed some small mistakes in the newly testsd code.
> Test `one_qubit_base` and `two_qubit_base` directly

- src/qibojit/custom_operators/__init__.py
- src/qibojit/custom_operators/backends.py
- src/qibojit/tests/conftest.py
- src/qibojit/tests/test_ops.py
In this PR, as already discussed, my aim is to add the [CuQuantum](https://github.com/NVIDIA/cuQuantum) library as a new qibojit backend in order to add it to the benchmarked libraries.
The new backend is an inheritance from the `CupyBackend` since they both use `cupy`.
I tried to run this very simple example
```python
from qibo.models import Circuit
from qibo import gates
c = Circuit(1)
c.add(gates.H(0))
ex = c()
print(ex)
``` 
and I obtained a `CUDA_ERROR_ILLEGAL_ADDRESS`, the same thing happens if I try to access the initial state after the circuit execution. I'm guessing that the problem may be related to the different way the state vector is treated in cuquantum.
For the implementation I am following this [example](https://github.com/NVIDIA/cuQuantum/blob/main/python/samples/gate_appl …
> Adding CuQuantum library

- .github/.codecov.yml
- src/qibojit/custom_operators/backends.py
- src/qibojit/custom_operators/raw_kernels.py
In this PR I'm going to implement an alternative approach for kernel loading/compilation.
The main goal is to reduce compilation times.
Two considerations:
- It seems like ``cp.RawKernel`` does not support templates.
- By loading and compiling each kernel independently, we compile many times the helper methods / device functions that are called by many different kernels, so that if a circuit uses all different gates, the compilation time will be worse.
I tried the following approach:
- Create a ``cp.RawModule`` for each kernel and each template specialization.
- Create a lambda function that calls each rawmodule only when it's needed.
Dry run overhead: ~ 0.8 s (qft), ~ 0.65 s (supremacy, variational), ~ 0.5 s (only a one-qubit gate) against ~ 3.2 s with the main branch.
Notice that this …
> Use RawKernel without name_expressions to enable CuPy cache

- src/qibojit/custom_operators/__init__.py
- src/qibojit/custom_operators/platforms.py
- src/qibojit/tests/test_gates.py
Fixes #62 by using `order='C'` in the platform cast methods. Added relevant tests that use `expm` too.
I suggest to keep this PR open until we confirm that tests in qiboteam/qibo#539 are passing for all platforms.
> Force C order casting for GPU

- setup.py
- src/qibojit/custom_operators/platforms.py
Following #63, I think the solution proposed in this PR is the cleanest, i.e. we avoid precompilation at installation time however during compilation (first import) the code prints a message explaining what is going on.
@stavros11 let me know if you agree.
> adding info message concerning compilation

- src/qibojit/custom_operators/__init__.py
- src/qibojit/custom_operators/platforms.py
Qibo backends have a `supports_multigpu` flag that specifies whether the underlying backend supports multigpu or no. Here I delegate this flag to platforms for the qibojit backend and I disable multigpu support for numba and cuquantum, leaving it only for cupy (following the discussion in qiboteam/qibo#539). 
The `supports_multigpu` flag is used by qiboteam/qibo#539 to decide for which backends we will run the multigpu tests as well as a few other parts of qibo code in order to raise errors if a distributed execution is attempted with a backend that does not support it. The only disadvantage of the implementation here is that multigpu using the numba backend is disabled, even though in principle works (despite everything is running on CPU). I believe it is better to have a clearer …
> Move `supports_multigpu` flag to platforms

- src/qibojit/custom_operators/platforms.py
- src/qibojit/tests/test_gates.py
- src/qibojit/tests/test_ops.py
Cuquantum tests are failing for #69 because `.get()` is now used on a numpy array. This should fix the issue. Using this version, both qibo and qibojit tests are passing for me on both my laptop and DGX, with and without cuquantum. Would be good to double check.
> Update qubits type for cuquantum

- src/qibojit/custom_operators/__init__.py
- src/qibojit/custom_operators/platforms.py
- src/qibojit/tests/test_gates.py
- src/qibojit/tests/test_ops.py
Fixes the multi-GPU memory grow observed the past weeks.
@stavros11 @andrea-pasquale please be careful, check and test if this works for you. I have spent 15 minutes to find the origin of this issue and 1 min to fix so please cross-check carefully my approach, in particular for cuQuantum. This also seems to fix the async issue during simulation run (GPUs start in sync after the dry-run).
> multi-gpu cupy memory grow fix attempt

- src/qibojit/custom_operators/platforms.py
In this PR I try to improve our cuquantum backend in order to reduce the dry run and the simulation time which are very different compared to our cupy backend in the case of some circuit like the QFT.
As suggested by the NVIDIA guys the implementation now uses only one handle which is initiated in the constructor and its destroyed in the destructor of the CuQuantum platform.
I'll upload some benchmarks shortly.
> Improving CuQuantum Implementation

- src/qibojit/custom_operators/__init__.py
- src/qibojit/custom_operators/platforms.py
- src/qibojit/tests/test_platforms.py
Required to enable qibo Hamiltonian creation using sparse matrices. Sparse matrices are supported for both numba (via `scipy.sparse`) and cupy/cuquantum (via `cupy.sparse`) platforms.
> Support sparse matrices in cast methods

- src/qibojit/custom_operators/__init__.py
- src/qibojit/tests/test_platforms.py
While fixing the tests of qiboteam/qibo#542 on GPU I was getting some failures associated with using `expm` on sparse matrices. This PR should fix this issue.
@andrea-pasquale when you have time, please try to run the qibojit and qibo tests using this branch (`fixexpm`) for qibojit and the `sparse` branch for qibo. All tests should now pass on CPU and GPU.
> Fix `expm` for sparse matrices on GPU

- src/qibojit/custom_operators/__init__.py
- src/qibojit/custom_operators/platforms.py
While working on a qibo callback I realized that qibojit creates copies, instead of using in-place updates, when simulating density matrices. This is true on CPU and GPU.
Here is a script to reproduce this issue:
```py
import numpy as np
from qibo import gates, K
from qibo.models import Circuit
state = np.zeros((4, 4), dtype=np.complex128)
state[0, 0] = 1
state = K.cast(state)
c = Circuit(2, density_matrix=True)
c.add(gates.H(0))
c.add(gates.H(1))
final_state = c(initial_state=state)
print(state)
print(final_state.state())
```
will print
```
[Qibo 0.1.8.dev0|INFO|2022-03-10 14:20:02]: Using qibojit (numba) backend on /CPU:0
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
[[0.25+0.j 0.25+0.j 0.25+0.j 0.25+0.j] …
```
> Change `.flatten()` to `.ravel()` to avoid copies

- src/qibojit/custom_operators/platforms.py
The latest version of qibojit fails when running multigpu circuits on a machine with multiple physical GPUs. For example the following minimal example:
```Python
from qibo import models, gates
circuit = models.Circuit(3, accelerators={"/GPU:0": 1, "/GPU:1": 1})
circuit.add(gates.H(0))
final_state = c()
print(final_state)
```
fails with
```
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
```
After checking earlier qibojit versions I realized that the error is associated with #74 and particularly because `.flatten()` was changed to `.ravel()` for some gate castings. This is fixed here and the above example works. Also, all tests are passing.
@scarrazza @andrea-pasquale, if you have access to a machine with multiple physical …
> Change `.ravel()` back to `.flatten()` for gates

- src/qibojit/custom_operators/platforms.py
Closes #76. This PR fixes a few bugs that we had with  [latest](https://docs.nvidia.com/cuda/cuquantum/python/release_notes.html#cuquantum-python-v22-03-0) version of cuquatum.
Now, both qibo and qibojit tests are passing on dom. @stavros11 when you have time please check if tests are passing also for you.
> Update cuQuantum version

- src/qibojit/backends.py
In this PR I've added the attributes `numeric_types` and `tensor_types` for both the cupy and the numba backend.
For cupy I've also added some methods to perform basic operations with hamiltonians. The reason for this is that in qiboteam/qibo#595 all the methods involving hamiltonian use only numpy, which was causing tests to fail in the same PR.
Using this branch qibo tests in qiboteam/qibo#595 are passing also for GPU.
> Implement methods for hamiltonians abstraction

- .github/workflows/rules.yml
- src/qibojit/backends/gpu.py
Fixes qibo/abstractions tests when using cuquantum. 
@andrea-pasquale when you have time, could you please try to run all qibo (on `abstractions` branch) and qibojit tests using numba, cupy and cuquantum and confirm that everything is working? After this small fix, all is okay from my side.
It would also be great if we could test AMD HIP given that we promise this feature because I do not have access to an AMD GPU and I cannot test this.
> Fix cuquantum tests

- src/qibojit/backends/cpu.py
- src/qibojit/backends/gpu.py
Similarly to qiboteam/qibo#643, I am adding the backend version as an attribute inside the backend class.
For this case I decided to store directly for each backend the `qibojit` version. 
I was also thinking that we could store directly the `numba` version or the `cupy` version.
Let me know what you prefer.
> Add version attribute in backends

- src/qibojit/backends/gpu.py
- src/qibojit/backends/matrices.py
qibo/backends/matrices.py is renamed to npmatrices.py and this updates qibojit imports accordingly. Only works with qiboteam/qibo#677.
> Fix qibo matrices import

- src/qibojit/backends/gpu.py
This PR fixes an issue raised by @scarrazza when running circuits with accelerators and measurement registers using cupy https://github.com/qiboteam/qibo/pull/769#issuecomment-1399516953. The issue can be reproduced by
```python
from qibo import gates, models
from qibo.backends import construct_backend
backend=construct_backend("qibojit", "cupy")
accelerators = {"/GPU:0": 1, "/GPU:1": 1}
c = models.Circuit(6, accelerators)
c.add([gates.X(0), gates.X(1), gates.X(3)])
ma = c.add(gates.M(5, 1, 3, register_name="a"))
mb = c.add(gates.M(2, 0, register_name="b"))
result = backend.execute_circuit(c, nshots=100)
ma_freq = ma.frequencies()
mb_freq = mb.frequencies()
frequencies = result.frequencies(registers=True)
```
> Measurements with registers on gpu (cupy)

- .github/workflows/deploy.yml
- .github/workflows/rules.yml
- setup.py
- src/qibojit/backends/cpu.py
- src/qibojit/tests/test_gates.py
- src/qibojit/tests/test_ops.py
- src/qibojit/tests/utils.py
This closed #108 and fixes test issues in https://github.com/qiboteam/qibo/pull/810
PS: I don't have permissions in this repo, this is why I'm pushing this fix from my fork.
> Fixes bug in `backend.apply_channel_density_matrix` for quantum-to-classical channels

- .github/workflows/deploy.yml
- .github/workflows/rules.yml
- setup.py
- src/qibojit/backends/gpu.py
- src/qibojit/backends/matrices.py
- src/qibojit/tests/test_ops.py
This PR implements the identity as a density matrix. It is necessary to use the `DepolarizingChannel` with density matrices on `cupy`, which is implemented in PR [819](https://github.com/qiboteam/qibo/pull/819).
> Identity density matrix

- pyproject.toml
Includes the `build-system` section so pip knows the version when installing from source.
> adding build system

- src/qibojit/backends/cpu.py
This is needed for https://github.com/qiboteam/qibo/pull/1373
> Add `gates.GeneralizedRBS` gate

- poetry.lock
- pyproject.toml
- src/qibojit/backends/gpu.py
`qibojit` equivalent to https://github.com/qiboteam/qibo/pull/1472 and needs to be merged after it
> Fix bug in `quantum_info.linalg_operations.matrix_power` for negative powers of singular matrices

- .github/workflows/selfhosted.yml
- src/qibojit/backends/clifford_operations_cpu.py
- src/qibojit/backends/cpu.py
- src/qibojit/custom_operators/ops.py
- src/qibojit/tests/test_backends.py
<del>Playing around with numba threading in combination with qiboteam/qibo#1561</del>
@andrea-pasquale this PR houses eventual fixes needed by qiboteam/qibo#1561.
> Fixes for GPU tests and GPU workflow

- src/qibojit/backends/gpu.py
- src/qibojit/custom_operators/raw_kernels.py
I actually realized that on #221 I was overcomplicating things. It is possible to fix this with a much smaller diff and a minimal change in the kernels (only for the initial state one). I used the same test:
```py
import numpy as np
from qibo import Circuit, gates, set_backend, set_dtype
c = Circuit(2)
c.add(gates.H(0))
c.add(gates.CNOT(0, 1))
set_backend("numpy")
target_state = c().state()
set_backend("qibojit", platform="cupy")
for dtype in ("float32", "float64", "complex64", "complex128"):
set_dtype(dtype)
final_state = c().state().get()
np.testing.assert_allclose(final_state, target_state)
```
and it also works here. @renatomello let me know if this also fixes the issues with the qibo tests.
Qibojit tests on GPU also pass on this branch (when ran locally).
> Fix cupy for real number precisions
